after_training: null
agent: tonic.torch.agents.DDPG()
before_training: null
checkpoint: last
environment: tonic.environments.Gym('Pendulum-v1')
environment_name: null
header: import tonic.torch; import tonic.environments; import gym
name: DDPG-Pendulum
parallel: 1
path: null
seed: 0
sequential: 1
test_environment: null
trainer: null
